name: Auto-update conda & mamba
on:
 schedule:
   - cron: "*/5 * * * *"
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.MINIFORGE_AUTOUPDATE_SSH_PRIVATE_KEY }}
      - uses: conda-incubator/setup-miniconda@e23d871804685e8c52189e5bd45e9145019f10af
        with:
          miniforge-variant: Miniforge3
          environment-file: .github/actions/autoupdate/environment.yml
      - run: python .github/actions/autoupdate/update.py
      - name: Create Pull Request
        id: cpr
        # This is the v3 tag but for security purposes we pin to the exact commit.
        uses: peter-evans/create-pull-request@052fc72b4198ba9fbc81b818c6e1859f747d49a8
        with:
          commit-message: "Update conda/mamba version"
          title: "Update conda/mamba version"
          body: |
            This PR was created by the autoupdate action as it detected that
            either the conda or mamba version has changed and thus should be
            updated in the configuration.

            Due to limitations of Github Actions, you will need to close/reopen
            the PR to get the actions running.
          branch: autoupdate-action
          delete-branch: true
