name: Auto-update conda & mamba
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@e23d871804685e8c52189e5bd45e9145019f10af
        with:
          miniforge-variant: Miniforge3
          environment-file: .github/actions/autoupdate/environment.yml
      - run: |
          conda info
          python .github/actions/autoupdate/update.py
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
